<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'claviers',
                'brand' => 'corsair',
                'name' => 'Clavier Mécanique RGB',
                'name_ar' => 'لوحة مفاتيح ميكانيكية RGB',
                'slug' => 'clavier-mecanique-rgb',
                'short_description' => 'Clavier mécanique avec switchs rouges, rétroéclairage RGB personnalisable et repose-poignets.',
                'description' => 'Clavier mécanique avec switchs rouges, rétroéclairage RGB personnalisable et repose-poignets. Connexion USB-C détachable.',
                'description_ar' => 'لوحة مفاتيح ميكانيكية بمفاتيح حمراء، إضاءة RGB قابلة للتخصيص ومسند للمعصم. اتصال USB-C قابل للفصل.',
                'price' => 15000,
                'compare_price' => 18000,
                'sku' => 'KBR-CSR-001',
                'stock_quantity' => 12,
                'specs' => [
                    'switch_type' => 'mécanique',
                    'switch_color' => 'Rouge',
                    'layout' => 'AZERTY',
                    'backlight' => true,
                    'backlight_type' => 'RGB',
                    'connectivity' => 'Fils',
                    'key_count' => 104,
                    'material' => 'Aluminium + ABS',
                ],
            ],
            [
                'category' => 'souris',
                'brand' => 'razer',
                'name' => 'Souris Gaming 16000 DPI',
                'name_ar' => 'فأرة ألعاب 16000 DPI',
                'slug' => 'souris-gaming-16000-dpi',
                'short_description' => 'Capteur optique 16000 DPI, 8 boutons programmables, RGB et poids ajustable.',
                'description' => 'Capteur optique 16000 DPI, 8 boutons programmables, RGB et poids ajustable. Idéale pour FPS et MOBA.',
                'description_ar' => 'مستشعر بصري 16000 DPI، 8 أزرار قابلة للبرمجة، إضاءة RGB ووزن قابل للتعديل. مثالية لألعاب FPS وMOBA.',
                'price' => 8500,
                'sku' => 'MOU-RAZ-001',
                'stock_quantity' => 20,
                'specs' => [
                    'dpi' => 16000,
                    'sensor' => 'Optique',
                    'weight_g' => 85,
                    'connectivity' => 'Fils',
                    'buttons' => 8,
                    'side_buttons' => 2,
                    'rgb' => true,
                    'material' => 'ABS',
                    'cable_length' => '1.8m',
                ],
            ],
            [
                'category' => 'casques',
                'brand' => 'hyperx',
                'name' => 'Casque Gaming 7.1',
                'name_ar' => 'سماعة ألعاب 7.1',
                'slug' => 'casque-gaming-7-1',
                'short_description' => 'Son surround 7.1, micro anti-bruit amovible et mousses confortables à mémoire de forme.',
                'description' => 'Son surround 7.1, micro anti-bruit amovible et mousses confortables à mémoire de forme.',
                'description_ar' => 'صوت محيطي 7.1، ميكروفون عازل للضوضاء قابل للفصل وإسفنجات مريحة بتقنية الذاكرة.',
                'price' => 12000,
                'sku' => 'HSK-HYP-001',
                'stock_quantity' => 8,
                'specs' => [
                    'driver_size' => '53mm',
                    'frequency_response' => '13Hz-27kHz',
                    'impedance' => '60Ω',
                    'surround' => '7.1',
                    'microphone' => true,
                    'mic_type' => 'Amovible',
                    'connectivity' => 'Fils',
                    'noise_cancelling' => false,
                    'weight_g' => 315,
                    'battery_life' => 'N/A',
                    'rgb' => true,
                ],
            ],
            [
                'category' => 'combos',
                'brand' => 'redragon',
                'name' => 'Combo Clavier + Souris RGB',
                'name_ar' => 'مجموعة لوحة مفاتيح وفأرة RGB',
                'slug' => 'combo-clavier-souris-rgb',
                'short_description' => 'Pack complet clavier mécanique + souris gaming RGB avec tapis inclus.',
                'description' => 'Pack complet clavier mécanique + souris gaming RGB avec tapis inclus. Idéal pour débuter.',
                'description_ar' => 'حزمة كاملة لوحة مفاتيح ميكانيكية + فأرة ألعاب RGB مع ورقة ماوس مرفقة. مثالية للمبتدئين.',
                'price' => 18500,
                'sku' => 'CMB-RDG-001',
                'stock_quantity' => 6,
                'specs' => [
                    'items' => 'Clavier + Souris + Tapis',
                    'keyboard_type' => 'Mécanique',
                    'mouse_sensor' => 'Optique',
                    'mouse_dpi' => 12000,
                    'connectivity' => 'Fils',
                    'rgb' => true,
                    'includes_mousepad' => true,
                ],
            ],
            [
                'category' => 'micro-webcam',
                'brand' => 'logitech',
                'name' => 'Micro Studio USB',
                'name_ar' => 'ميكروفون استوديو USB',
                'slug' => 'micro-studio-usb',
                'short_description' => 'Micro condensateur USB avec capsule cardioïde, gain et mute tactile.',
                'description' => 'Micro condensateur USB avec capsule cardioïde, gain et mute tactile. Plug and play sur PC et console.',
                'description_ar' => 'ميكروفون مكثف USB مع نمط قلبي، تحكم بالكسب وكتم باللمس. يعمل مباشرة على الحاسوب والكونسول.',
                'price' => 9500,
                'sku' => 'MIC-LOG-001',
                'stock_quantity' => 10,
                'specs' => [
                    'type' => 'Micro',
                    'connection' => 'USB',
                    'pattern' => 'Cardioïde',
                    'sample_rate' => '96kHz',
                    'bit_depth' => '24-bit',
                    'noise_cancelling' => true,
                    'built_in_mic' => false,
                    'tripod_mount' => true,
                ],
            ],
            [
                'category' => 'micro-webcam',
                'brand' => 'logitech',
                'name' => 'Webcam Full HD 1080p',
                'name_ar' => 'كاميرا ويب Full HD 1080p',
                'slug' => 'webcam-full-hd-1080p',
                'short_description' => 'Webcam 1080p à 60 FPS avec double micro, champ de vision 90°.',
                'description' => 'Webcam 1080p à 60 FPS avec double micro, champ de vision 90° et correction automatique de la lumière.',
                'description_ar' => 'كاميرا ويب 1080p بمعدل 60 إطارًا، ميكروفون مزدوج، زاوية رؤية 90 درجة وتصحيح تلقائي للإضاءة.',
                'price' => 6800,
                'sku' => 'CAM-LOG-001',
                'stock_quantity' => 15,
                'specs' => [
                    'type' => 'Webcam',
                    'resolution' => '1080p',
                    'fps' => 60,
                    'fov' => '90°',
                    'autofocus' => true,
                    'low_light' => true,
                    'noise_cancelling' => true,
                    'built_in_mic' => true,
                    'tripod_mount' => false,
                ],
            ],
            [
                'category' => 'deco-gaming',
                'brand' => 'nzxt',
                'name' => 'Lampe LED Gaming',
                'name_ar' => 'مصباح LED للألعاب',
                'slug' => 'lampe-led-gaming',
                'short_description' => 'Bande LED RGB 2 mètres contrôlable par télécommande, 16 millions de couleurs.',
                'description' => 'Bande LED RGB 2 mètres contrôlable par télécommande, 16 millions de couleurs et plusieurs modes.',
                'description_ar' => 'شريط LED RGB بطول 2 متر يُتحكم فيه عن بعد، 16 مليون لون وعدة أوضاع.',
                'price' => 4200,
                'sku' => 'DEC-NZX-001',
                'stock_quantity' => 25,
                'specs' => [
                    'type' => 'Bande LED',
                    'power' => '24W',
                    'voltage' => '12V',
                    'color' => 'RGB',
                    'rgb' => true,
                    'length' => '2m',
                    'material' => 'Silicone',
                    'compatibility' => 'Alexa, Google Home, App mobile',
                ],
            ],
            [
                'category' => 'manettes',
                'brand' => 'logitech',
                'name' => 'Manette Bluetooth',
                'name_ar' => 'يد تحكم بلوتوث',
                'slug' => 'manette-bluetooth',
                'short_description' => 'Manette sans fil Bluetooth avec gâchettes analogiques et vibration.',
                'description' => 'Manette sans fil Bluetooth avec gâchettes analogiques, vibration et batterie longue durée.',
                'description_ar' => 'يد تحكم لاسلكية بلوتوث بزنادين تماثليين، اهتزاز وبطارية طويلة الأمد.',
                'price' => 11000,
                'sku' => 'CTL-LOG-001',
                'stock_quantity' => 9,
                'specs' => [
                    'connectivity' => 'Bluetooth',
                    'compatibility' => 'PC, PS3, Android',
                    'vibration' => true,
                    'gyroscope' => false,
                    'battery_life' => '40h',
                    'analog_triggers' => true,
                    'paddles' => 0,
                    'color' => 'Noir',
                ],
            ],
            [
                'category' => 'tapis-de-souris',
                'brand' => 'corsair',
                'name' => 'Tapis XXL RGB',
                'name_ar' => 'ورقة ماوس XXL RGB',
                'slug' => 'tapis-xxl-rgb',
                'short_description' => 'Tapis de souris XXL 900x400 mm avec liseré RGB.',
                'description' => 'Tapis de souris XXL 900x400 mm avec liseré RGB, surface micro-tissu et base antidérapante.',
                'description_ar' => 'ورقة ماوس XXL 900×400 ملم بحافة RGB، سطح من القماش الدقيق وقاعدة مانعة للانزلاق.',
                'price' => 3800,
                'sku' => 'PAD-CSR-001',
                'stock_quantity' => 30,
                'specs' => [
                    'dimensions' => '900x400x4mm',
                    'surface' => 'Tissu',
                    'base' => 'Antidérapante',
                    'thickness' => '4mm',
                    'edge_stitching' => true,
                    'rgb' => true,
                    'rgb_zones' => 4,
                ],
            ],
            [
                'category' => 'deco-gaming',
                'brand' => 'cooler-master',
                'name' => 'Support Casque RGB',
                'name_ar' => 'حامل سماعات RGB',
                'slug' => 'support-casque-rgb',
                'short_description' => 'Support casque en métal avec base RGB et 2 ports USB 3.0.',
                'description' => 'Support casque en métal avec base RGB et 2 ports USB 3.0.',
                'description_ar' => 'حامل سماعات معدني بقاعدة RGB ومنفذي USB 3.0.',
                'price' => 2900,
                'sku' => 'DEC-CMR-001',
                'stock_quantity' => 18,
                'specs' => [
                    'type' => 'Support casque',
                    'power' => '5V USB',
                    'voltage' => '5V',
                    'color' => 'Noir',
                    'rgb' => true,
                    'material' => 'Métal + ABS',
                    'compatibility' => 'Tous casques',
                ],
            ],
            [
                'category' => 'deco-gaming',
                'brand' => 'deepcool',
                'name' => 'Chargeur Rapide 65W',
                'name_ar' => 'شاحن سريع 65W',
                'slug' => 'chargeur-rapide-65w',
                'short_description' => 'Chargeur GaN 65W avec 2 ports USB-C et 1 USB-A.',
                'description' => 'Chargeur GaN 65W avec 2 ports USB-C et 1 USB-A. Compatible laptop, console et smartphone.',
                'description_ar' => 'شاحن GaN 65W بمنفذين USB-C ومنفذ USB-A. متوافق مع الحاسوب والكونسول والهاتف.',
                'price' => 5200,
                'sku' => 'ACC-DCP-001',
                'stock_quantity' => 22,
                'specs' => [
                    'type' => 'Chargeur GaN',
                    'power' => '65W',
                    'voltage' => '100-240V',
                    'compatibility' => 'Laptop, Console, Smartphone',
                ],
            ],
            [
                'category' => 'deco-gaming',
                'brand' => 'cooler-master',
                'name' => 'Refroidisseur Laptop RGB',
                'name_ar' => 'مبرد كمبيوتر محمول RGB',
                'slug' => 'refroidisseur-laptop-rgb',
                'short_description' => 'Support ventilé 6 fans RGB pour laptops 15-17".',
                'description' => 'Support ventilé 6 fans RGB pour laptops 15-17", réglage de vitesse et faible bruit.',
                'description_ar' => 'قاعدة مبردة بـ 6 مراوح RGB لأجهزة 15-17 بوصة، تحكم بالسرعة وضوضاء منخفضة.',
                'price' => 7500,
                'sku' => 'ACC-CMR-002',
                'stock_quantity' => 11,
                'specs' => [
                    'type' => 'Refroidisseur laptop',
                    'power' => 'USB 5V',
                    'voltage' => '5V',
                    'fan_size' => '140mm x6',
                    'rgb' => true,
                    'material' => 'Métal + ABS',
                    'compatibility' => 'Laptops 15-17"',
                ],
            ],
        ];

        foreach ($products as $product) {
            $category = Category::where('slug', $product['category'])->first();
            $brand = Brand::where('slug', $product['brand'])->first();

            if (! $category) {
                continue;
            }

            Product::updateOrCreate(
                ['slug' => $product['slug']],
                [
                    'category_id' => $category->id,
                    'brand_id' => $brand?->id,
                    'name' => $product['name'],
                    'name_ar' => $product['name_ar'],
                    'short_description' => $product['short_description'] ?? null,
                    'description' => $product['description'],
                    'description_ar' => $product['description_ar'],
                    'price' => $product['price'],
                    'compare_price' => $product['compare_price'] ?? null,
                    'sku' => $product['sku'],
                    'stock_quantity' => $product['stock_quantity'],
                    'specs' => $product['specs'],
                    'is_active' => true,
                    'is_featured' => in_array($product['slug'], ['clavier-mecanique-rgb', 'souris-gaming-16000-dpi', 'casque-gaming-7-1', 'micro-studio-usb']),
                ]
            );
        }
    }
}
